#!/usr/bin/env php
<?php
/**
 * Generate SQL to seed realistic SMS history into a demo database, by
 * copying sms/smsdelivery rows from another (real) Jethro database,
 * remapping person ids onto the target's (usually much smaller) person
 * pool, and replacing the source organisation's name with a generic
 * placeholder.
 *
 * Originally written to copy live SMS history from the coastec instance into
 * je_demo. Source person ids are mapped round-robin onto the target's person
 * pool (deterministic, order-preserving), with within-send deduping where
 * multiple source persons collapse onto the same target person.
 *
 * This script only READS from the source/target databases (to build the
 * person mapping and source rows) and WRITES NOTHING itself — it emits SQL
 * INSERT statements to stdout for you to review and run yourself, e.g.:
 *
 *   php scripts/seed_sms_from_coastec.php > /tmp/seed.sql
 *   less /tmp/seed.sql
 *   mysql je_demo < /tmp/seed.sql
 *
 * Requires a MySQL user with privileges on both the source and target
 * databases (e.g. run as the box owner via unix_socket auth — the app's own
 * runtime DB user normally only has access to its own database).
 *
 * Usage:
 *   php scripts/seed_sms_from_coastec.php --source-db=je_coastec --target-db=je_demo \
 *       --replace="CoastEC=church" --replace="Coast=church" > seed.sql
 */

function fail(string $msg): never
{
	fwrite(STDERR, "$msg\n");
	exit(1);
}

$opts = getopt('', ['source-db:', 'target-db:', 'replace:']);
$sourceDb = $opts['source-db'] ?? 'je_coastec';
$targetDb = $opts['target-db'] ?? 'je_demo';

$replacements = [];
foreach ((array)($opts['replace'] ?? []) as $pair) {
	[$search, $replace] = array_pad(explode('=', $pair, 2), 2, '');
	if ($search === '') fail("Invalid --replace value '$pair'; expected SEARCH=REPLACE");
	$replacements[$search] = $replace;
}
if (!$replacements) {
	// Defaults match the original coastec -> je_demo seeding.
	// Longest match first, so 'CoastECs' becomes 'churchs', not 'church' + 'EC' + 's'.
	$replacements = ['CoastEC' => 'church', 'Coast' => 'church'];
}

$db = mysqli_connect('localhost', get_current_user(), '', null)
	or fail('Connect failed: ' . mysqli_connect_error());
mysqli_set_charset($db, 'utf8mb4');

function q(mysqli $db, string $sql): mysqli_result|bool
{
	$r = mysqli_query($db, $sql);
	if ($r === false) fail("Query failed: $sql\n" . mysqli_error($db));
	return $r;
}

function applyReplacements(?string $s, array $replacements): ?string
{
	if ($s === null) return null;
	foreach ($replacements as $search => $replace) {
		$s = str_replace($search, $replace, $s);
	}
	return $s;
}

function sqlLiteral(mysqli $db, ?string $s): string
{
	return $s === null ? 'NULL' : ("'" . mysqli_real_escape_string($db, $s) . "'");
}

// --- Build deterministic source-person -> target-person mapping ---

$targetIds = [];
$res = q($db, "SELECT id FROM `$targetDb`._person ORDER BY id");
while ($row = mysqli_fetch_assoc($res)) $targetIds[] = (int)$row['id'];
$numTarget = count($targetIds);
if ($numTarget === 0) fail("$targetDb has no persons; aborting");

$sourceIds = [];
$res = q($db, "
	SELECT DISTINCT id FROM (
		SELECT sender AS id FROM `$sourceDb`.sms WHERE sender IS NOT NULL
		UNION
		SELECT personid AS id FROM `$sourceDb`.smsdelivery WHERE personid IS NOT NULL
	) u ORDER BY id
");
while ($row = mysqli_fetch_assoc($res)) $sourceIds[] = (int)$row['id'];

$personMap = []; // source_id => target_id
foreach ($sourceIds as $i => $sid) {
	$personMap[$sid] = $targetIds[$i % $numTarget];
}

$smsTotal = mysqli_fetch_row(q($db, "SELECT COUNT(*) FROM `$sourceDb`.sms"))[0];
$deliveryTotal = mysqli_fetch_row(q($db, "SELECT COUNT(*) FROM `$sourceDb`.smsdelivery"))[0];

fwrite(STDERR, "Source: $sourceDb ($smsTotal sms, $deliveryTotal smsdelivery rows)\n");
fwrite(STDERR, "Target: $targetDb ($numTarget persons)\n");
fwrite(STDERR, "Mapping " . count($sourceIds) . " source persons onto $numTarget target persons (round-robin).\n");
fwrite(STDERR, "Replacements: " . json_encode($replacements) . "\n");
fwrite(STDERR, "Emitting SQL to stdout. Nothing has been written to any database.\n");

// --- Emit INSERT statements ---
// Each sms row uses a MySQL user variable to capture its auto-increment id
// (via LAST_INSERT_ID()) so the matching smsdelivery rows can reference it
// without us knowing the target id in advance.

echo "-- Generated by scripts/seed_sms_from_coastec.php\n";
echo "-- Source: $sourceDb  Target: $targetDb\n";
echo "START TRANSACTION;\n\n";

$smsCount = 0;
$deliveryCount = 0;

$smsRes = q($db, "SELECT id, body, sender, created, scheduled_send_at FROM `$sourceDb`.sms ORDER BY id");
while ($sms = mysqli_fetch_assoc($smsRes)) {
	$oldSmsId = (int)$sms['id'];
	$newBody = applyReplacements($sms['body'], $replacements);
	$newSender = $sms['sender'] !== null ? ($personMap[(int)$sms['sender']] ?? null) : null;

	echo "INSERT INTO `$targetDb`.sms (body, sender, created, scheduled_send_at) VALUES ("
		. sqlLiteral($db, $newBody) . ", "
		. ($newSender ?? 'NULL') . ", "
		. sqlLiteral($db, $sms['created']) . ", "
		. sqlLiteral($db, $sms['scheduled_send_at']) . ");\n";
	echo "SET @last_sms_id = LAST_INSERT_ID();\n";
	$smsCount++;

	// Map + dedupe recipients (collisions happen whenever the source person
	// pool is larger than the target's).
	$seenTargetPersons = [];
	$delRes = q($db, "SELECT personid, status FROM `$sourceDb`.smsdelivery WHERE sms_id = $oldSmsId ORDER BY id");
	while ($d = mysqli_fetch_assoc($delRes)) {
		if ($d['personid'] === null) continue; // raw-mobile-number deliveries have no person to remap onto
		$srcPid = (int)$d['personid'];
		$targetPid = $personMap[$srcPid] ?? null;
		if ($targetPid === null || isset($seenTargetPersons[$targetPid])) continue;
		$seenTargetPersons[$targetPid] = true;

		echo "INSERT INTO `$targetDb`.smsdelivery (sms_id, personid, status) VALUES (@last_sms_id, $targetPid, "
			. sqlLiteral($db, $d['status']) . ");\n";
		$deliveryCount++;
	}
	echo "\n";
}

echo "COMMIT;\n";

fwrite(STDERR, "Generated SQL for $smsCount sms rows and $deliveryCount smsdelivery rows.\n");
